services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - ./.volumes/frontend:/app/data
    depends_on:
      - api-gateway
    networks:
      - app-network

  api-gateway:
    build: ./api-gateway
    ports:
      - "8000:8000"
    volumes:
      - ./api-gateway:/app
      - ./.volumes/api-gateway:/app/data
    env_file:
      - ./api-gateway/.env
    depends_on:
      - sync-processor
      - async-processor
    networks:
      - app-network

  sync-processor:
    build: ./sync-processor
    ports:
      - "8001:8001"
    volumes:
      - ./sync-processor:/app
      - ./.volumes/sync-processor:/app/data
    env_file:
      - ./sync-processor/.env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
